linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  nakedret:
    max-func-lines: 100
  dupl:
    threshold: 100
  funlen:
    lines: 80
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  govet:
    check-shadowing: false
  depguard:
    list-type: blacklist
  misspell:
    locale: US
  lll:
    line-length: 100
    tab-width: 4
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentFormatting # https://github.com/go-critic/go-critic/issues/755

linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gosec
    - gochecknoinits
    - gochecknoglobals
    - typecheck
    - wsl
  fast: true

run:
  skip-files:
    - .*_test.go
    - swagger.go

issues:
  exclude-use-default: false
