projectGroup: pfe
projectName: smart-wallet

### Slack
channel: git_pfe

### Test
runTests: true
testCommandFlag: "test ./..."
#testFolderPath: test/

### Build
buildCommand: "make build"
buildOutputFolder: ""
outputFilePattern: smart-wallet

### Deploy
deployUponTestSuccess: true

### Upload
uploadArtifacts: true

### Sonarqube analysis
sonarqubeTest: true
sonarProjectKey: smart-wallet
sonarSources: .
