// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"encoding/json"
	"time"
)

type RoutineTransactionPolicy struct {
	ID                int64     `json:"id"`
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	NymID             string    `json:"nym_id"`
	CreatedAt         time.Time `json:"created_at"`
	ScheduleStartDate time.Time `json:"schedule_start_date"`
	ScheduleEndDate   time.Time `json:"schedule_end_date"`
	Frequency         string    `json:"frequency"`
	Amount            int32     `json:"amount"`
}

type Transaction struct {
	ID               int64           `json:"id"`
	NymID            string          `json:"nym_id"`
	TransferSequence int32           `json:"transfer_sequence"`
	Transfer         json.RawMessage `json:"transfer"`
	PolicyID         int64           `json:"policy_id"`
}

type TransactionTriggerPolicy struct {
	ID              int64           `json:"id"`
	Name            string          `json:"name"`
	Description     string          `json:"description"`
	NymID           string          `json:"nym_id"`
	CreatedAt       time.Time       `json:"created_at"`
	TargetedBalance json.RawMessage `json:"targeted_balance"`
	Amount          int32           `json:"amount"`
}

type UserPolicy struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	NymID       string    `json:"nym_id"`
	CreatedAt   time.Time `json:"created_at"`
}
