// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type RoutineTransactionPolicy struct {
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	Sender            string    `json:"sender"`
	Receiver          string    `json:"receiver"`
	CreatedAt         time.Time `json:"created_at"`
	ScheduleStartDate time.Time `json:"schedule_start_date"`
	ScheduleEndDate   time.Time `json:"schedule_end_date"`
	Frequency         string    `json:"frequency"`
	Amount            int32     `json:"amount"`
}

type Transaction struct {
	ID               int64         `json:"id"`
	NymID            string        `json:"nym_id"`
	TransferSequence int32         `json:"transfer_sequence"`
	PolicyID         sql.NullInt64 `json:"policy_id"`
}

type TransactionTriggerPolicy struct {
	Name            string          `json:"name"`
	Description     string          `json:"description"`
	Sender          string          `json:"sender"`
	Receiver        string          `json:"receiver"`
	CreatedAt       time.Time       `json:"created_at"`
	TargetedBalance json.RawMessage `json:"targeted_balance"`
	Repeated        int32           `json:"repeated"`
	Amount          int32           `json:"amount"`
}

type UserPolicy struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Sender      string    `json:"sender"`
	Receiver    string    `json:"receiver"`
	CreatedAt   time.Time `json:"created_at"`
}
