// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateRoutineTransactionPolicy(ctx context.Context, arg CreateRoutineTransactionPolicyParams) (RoutineTransactionPolicy, error)
	CreateTransactionTriggerPolicy(ctx context.Context, arg CreateTransactionTriggerPolicyParams) (TransactionTriggerPolicy, error)
	DeleteRoutineTransactionPolicy(ctx context.Context, id int64) error
	DeleteTransactionTriggerPolicy(ctx context.Context, id int64) error
	DeleteUserPolicy(ctx context.Context, id int64) error
	GetRoutineTransactionPolicy(ctx context.Context, id int64) (RoutineTransactionPolicy, error)
	GetTransactionTriggerPolicy(ctx context.Context, id int64) (TransactionTriggerPolicy, error)
	GetUserPolicy(ctx context.Context, id int64) (GetUserPolicyRow, error)
	ListRoutineTransactionPolicies(ctx context.Context, arg ListRoutineTransactionPoliciesParams) ([]RoutineTransactionPolicy, error)
	ListTransactionTriggerPolicies(ctx context.Context, arg ListTransactionTriggerPoliciesParams) ([]TransactionTriggerPolicy, error)
	ListUserPolicies(ctx context.Context, arg ListUserPoliciesParams) ([]UserPolicy, error)
	UpdateRoutineTransactionPolicy(ctx context.Context, arg UpdateRoutineTransactionPolicyParams) (RoutineTransactionPolicy, error)
	UpdateTransactionTriggerPolicy(ctx context.Context, arg UpdateTransactionTriggerPolicyParams) (TransactionTriggerPolicy, error)
}

var _ Querier = (*Queries)(nil)
