// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"encoding/json"
	"time"

	"git.digitus.me/prosperus/protocol/identity"
	"git.digitus.me/prosperus/protocol/types"
)

type RoutineTransactionPolicy struct {
	ID                int64              `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	NymID             identity.PublicKey `json:"nymID"`
	Recipient         identity.PublicKey `json:"recipient"`
	CreatedAt         time.Time          `json:"createdAt"`
	ScheduleStartDate time.Time          `json:"scheduleStartDate"`
	ScheduleEndDate   time.Time          `json:"scheduleEndDate"`
	Frequency         string             `json:"frequency"`
	Amount            types.Balance      `json:"amount"`
}

type Transaction struct {
	ID               int64           `json:"id"`
	NymID            string          `json:"nymID"`
	TransferSequence int32           `json:"transferSequence"`
	Transfer         json.RawMessage `json:"transfer"`
	PolicyID         int64           `json:"policyID"`
}

type TransactionTriggerPolicy struct {
	ID              int64              `json:"id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	NymID           identity.PublicKey `json:"nymID"`
	Recipient       identity.PublicKey `json:"recipient"`
	CreatedAt       time.Time          `json:"createdAt"`
	TargetedBalance types.Balance      `json:"targetedBalance"`
	Amount          types.Balance      `json:"amount"`
}

type UserPolicy struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	NymID       string    `json:"nymID"`
	Recipient   string    `json:"recipient"`
	CreatedAt   time.Time `json:"createdAt"`
}
