// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
)

type Querier interface {
	CreateRTP(ctx context.Context, arg CreateRTPParams) (RoutineTransactionPolicy, error)
	CreateTTP(ctx context.Context, arg CreateTTPParams) (TransactionTriggerPolicy, error)
	DeleteRTP(ctx context.Context, id int64) error
	DeleteTTP(ctx context.Context, id int64) error
	DeleteUserPolicy(ctx context.Context, id int64) error
	GetRTP(ctx context.Context, id int64) (RoutineTransactionPolicy, error)
	GetTTP(ctx context.Context, id int64) (TransactionTriggerPolicy, error)
	GetUserPolicy(ctx context.Context, id int64) (GetUserPolicyRow, error)
	ListRTP(ctx context.Context, arg ListRTPParams) ([]RoutineTransactionPolicy, error)
	ListTTP(ctx context.Context, arg ListTTPParams) ([]TransactionTriggerPolicy, error)
	ListUserPolicies(ctx context.Context, arg ListUserPoliciesParams) ([]UserPolicy, error)
	UpdateRTP(ctx context.Context, arg UpdateRTPParams) (RoutineTransactionPolicy, error)
	UpdateTTP(ctx context.Context, arg UpdateTTPParams) (TransactionTriggerPolicy, error)
}

var _ Querier = (*Queries)(nil)
