definitions:
  api.TTPRequest:
    properties:
      amount:
        $ref: '#/definitions/types.Balance'
      description:
        type: string
      name:
        type: string
      recipient:
        items:
          type: integer
        type: array
      targetedBalance:
        $ref: '#/definitions/types.Balance'
    required:
    - amount
    - description
    - name
    - recipient
    - targetedBalance
    type: object
  api.listTransactionTriggerPoliciesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/types.TransactionTriggerPolicy'
        type: array
      total:
        type: integer
    type: object
  types.Balance:
    additionalProperties: {"type": "string", "enum": ["Contributor", "User"]}
    type: object
  types.TransactionTriggerPolicy:
    properties:
      amount:
        $ref: '#/definitions/types.Balance'
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      nymID:
        items:
          type: integer
        type: array
      recipient:
        items:
          type: integer
        type: array
      targetedBalance:
        $ref: '#/definitions/types.Balance'
    type: object
info:
  contact: {}
  description: ProsperUs Smart wallet
  title: Smart Wallet
  version: 0.0.0
paths:
  /api/:nym-id/transaction-trigger-policy:
    get:
      description: Get all transaction trigger policies
      operationId: list-transaction-trigger-policy
      parameters:
      - description: NymID
        in: path
        name: nym-id
        required: true
        type: string
      - in: query
        name: itemsPerPage
        required: true
        type: integer
      - in: query
        name: page
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.listTransactionTriggerPoliciesResponse'
      tags:
      - transaction-trigger-policy
    post:
      description: Create a transaction trigger policy
      operationId: create-transaction-trigger-policy
      parameters:
      - description: NymID
        in: path
        name: nym-id
        required: true
        type: string
      - description: Transation Trigger Policy
        in: body
        name: TTPRequest
        required: true
        schema:
          $ref: '#/definitions/api.TTPRequest'
      responses:
        "201":
          description: ""
      tags:
      - transaction-trigger-policy
  /api/:nym-id/transaction-trigger-policy/:id:
    delete:
      description: Delete a transaction trigger policy
      operationId: delete-transaction-trigger-policy
      parameters:
      - description: NymID
        in: path
        name: nym-id
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: ""
      tags:
      - transaction-trigger-policy
    get:
      description: Get a transaction trigger policy
      operationId: get-transaction-trigger-policy
      parameters:
      - description: NymID
        in: path
        name: nym-id
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.TransactionTriggerPolicy'
      tags:
      - transaction-trigger-policy
    put:
      description: Update a transaction trigger policy
      operationId: update-transaction-trigger-policy
      parameters:
      - description: NymID
        in: path
        name: nym-id
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Transation Trigger Policy
        in: body
        name: TTPRequest
        required: true
        schema:
          $ref: '#/definitions/api.TTPRequest'
      responses:
        "200":
          description: ""
      tags:
      - transaction-trigger-policy
swagger: "2.0"
